version: "3.6"
volumes:
  data:
services:
  db:
    container_name: mysql
    image: mysql:8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
       - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appLocal
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev

  app:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - "db"
    ports:
      - 8080:80
    depends_on:
      - db